### PR TITLE
Added a Integration Test. please review this code 

### PR DESCRIPTION
**Pull request by Josh0104**
I used AngelSharp package to read the content from the html body. If there is any confusion at the code, please inform me here, so we can make the code more understandable and readable for you. I also takes any question you have regarding this pull request :)

### CODE REVIEW

**Review by hananinas — COMMENTED** [review]
Looks good the sln has been changed to suit the structure of the  project.

**Review by hananinas — COMMENTED** [review]
Unit test looks fine.

**Review by hananinas — COMMENTED** [review]
Can you change the name of this folder to match the project structure.

**Comment by Josh0104** [comment]
I have now changed the. Chirp.sln so it should work now

**Pull request closed without merging**
